version: 2.1

jobs:
  request_specs:
    docker:
      - image: circleci/ruby:3.1
      - image: circleci/postgres:14.5
        environment:
          POSTGRES_USER: postgres
          POSTGRES_DB: test_db
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            sudo apt-get update
            sudo apt-get install -y nodejs postgresql-client
            gem install bundler
            bundle install
      - run:
          name: Setup database
          command: |
            bin/rails db:create
            bin/rails db:schema:load
      - run:
          name: Run request specs
          command: bundle exec rspec spec/requests

workflows:
  version: 2
  test:
    jobs:
      - request_specs
